#!/usr/bin/env bash
# start.sh — Start LangFuse local stack for PM-OS
#
# Usage:
#   cd langfuse && ./start.sh        # start (generates .env if missing)
#   cd langfuse && ./start.sh stop    # stop all services
#   cd langfuse && ./start.sh status  # show service status
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# ─── Commands ────────────────────────────────────────────────────────────────

case "${1:-start}" in
  stop)
    echo "Stopping LangFuse..."
    docker compose down
    exit 0
    ;;
  status)
    docker compose ps
    exit 0
    ;;
  start) ;;
  *)
    echo "Usage: $0 [start|stop|status]"
    exit 1
    ;;
esac

# ─── Check Docker ────────────────────────────────────────────────────────────

if ! command -v docker &>/dev/null; then
  echo "ERROR: Docker is not installed. Install Docker Desktop first."
  exit 1
fi

if ! docker info &>/dev/null; then
  echo "ERROR: Docker daemon is not running. Start Docker Desktop first."
  exit 1
fi

# ─── Generate .env if missing ────────────────────────────────────────────────

if [ ! -f .env ]; then
  echo "Generating .env with random secrets..."

  NEXTAUTH_SECRET=$(openssl rand -base64 32)
  SALT=$(openssl rand -base64 16)
  ENCRYPTION_KEY=$(openssl rand -hex 32)
  CLICKHOUSE_PASSWORD=$(openssl rand -base64 16 | tr -d '=/+' | head -c 20)
  MINIO_ROOT_PASSWORD=$(openssl rand -base64 16 | tr -d '=/+' | head -c 20)
  REDIS_AUTH=$(openssl rand -base64 16 | tr -d '=/+' | head -c 20)
  # Pre-generate API keys so scripts can use them immediately
  PUBLIC_KEY="pk-lf-$(openssl rand -hex 12)"
  SECRET_KEY="sk-lf-$(openssl rand -hex 24)"

  cat > .env <<EOF
# LangFuse secrets — auto-generated by start.sh
# These are local-only. Do not commit this file.

NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
SALT=${SALT}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
REDIS_AUTH=${REDIS_AUTH}

# Auto-provisioned project API keys (used by scripts/langfuse_client.py)
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=${PUBLIC_KEY}
LANGFUSE_INIT_PROJECT_SECRET_KEY=${SECRET_KEY}

# Default user (change password after first login)
LANGFUSE_INIT_USER_EMAIL=jay@pm-os.local
LANGFUSE_INIT_USER_NAME=Jay
LANGFUSE_INIT_USER_PASSWORD=changeme123
EOF

  echo "Generated .env with secrets."
  echo ""
  echo "API keys for your scripts:"
  echo "  LANGFUSE_PUBLIC_KEY=${PUBLIC_KEY}"
  echo "  LANGFUSE_SECRET_KEY=${SECRET_KEY}"
  echo ""
  echo "Default login: jay@pm-os.local / changeme123"
  echo ""
fi

# ─── Start services ──────────────────────────────────────────────────────────

echo "Starting LangFuse..."
docker compose up -d

echo ""
echo "Waiting for services to be healthy..."
# Wait up to 120s for web to be ready
for i in $(seq 1 60); do
  if curl -sf http://localhost:3000 >/dev/null 2>&1; then
    echo ""
    echo "LangFuse is ready!"
    echo "  UI:  http://localhost:3000"
    echo "  Login: jay@pm-os.local / changeme123"
    echo ""

    # Extract API keys from .env for convenience
    if grep -q LANGFUSE_INIT_PROJECT_PUBLIC_KEY .env; then
      PK=$(grep LANGFUSE_INIT_PROJECT_PUBLIC_KEY .env | cut -d= -f2)
      SK=$(grep LANGFUSE_INIT_PROJECT_SECRET_KEY .env | cut -d= -f2)
      echo "Add to your shell profile or .env:"
      echo "  export LANGFUSE_PUBLIC_KEY=${PK}"
      echo "  export LANGFUSE_SECRET_KEY=${SK}"
      echo "  export LANGFUSE_HOST=http://localhost:3000"
    fi
    exit 0
  fi
  printf "."
  sleep 2
done

echo ""
echo "WARNING: LangFuse did not become ready within 120s."
echo "Check logs with: cd langfuse && docker compose logs"
exit 1
