#!/usr/bin/env bash
# setup_doc_sync.sh — One-time setup for bidirectional MD <-> Word sync.
#
# Installs dependencies, detects OneDrive path, creates config,
# generates pandoc reference template, and installs launchd watcher.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PM_OS_DIR="$(dirname "$SCRIPT_DIR")"
PLIST_NAME="com.pm-os.doc-sync"
PLIST_PATH="$HOME/Library/LaunchAgents/${PLIST_NAME}.plist"

echo "=== PM-OS Document Sync Setup ==="
echo

# ─── 1. Install dependencies ─────────────────────────────────────────────────

echo "Step 1: Checking dependencies..."

if ! command -v pandoc &>/dev/null; then
    echo "  Installing pandoc..."
    brew install pandoc
else
    echo "  pandoc: $(pandoc --version | head -1)"
fi

if ! command -v fswatch &>/dev/null; then
    echo "  Installing fswatch..."
    brew install fswatch
else
    echo "  fswatch: installed"
fi

echo

# ─── 2. Detect OneDrive folder ───────────────────────────────────────────────

echo "Step 2: Detecting OneDrive folder..."

ONEDRIVE_ROOT=""
for dir in "$HOME/Library/CloudStorage"/OneDrive-*/; do
    if [ -d "$dir" ]; then
        ONEDRIVE_ROOT="$dir"
        break
    fi
done

# Fallback to plain OneDrive
if [ -z "$ONEDRIVE_ROOT" ] && [ -d "$HOME/Library/CloudStorage/OneDrive" ]; then
    ONEDRIVE_ROOT="$HOME/Library/CloudStorage/OneDrive"
fi

if [ -z "$ONEDRIVE_ROOT" ]; then
    echo "  OneDrive folder not found at ~/Library/CloudStorage/OneDrive-*"
    echo "  Please install and sign in to OneDrive for Mac first."
    echo
    read -rp "  Enter your OneDrive path manually (or press Enter to skip): " ONEDRIVE_ROOT
    if [ -z "$ONEDRIVE_ROOT" ]; then
        echo "  Skipping OneDrive setup. Edit scripts/sync_config.yaml manually."
        ONEDRIVE_ROOT="~/Library/CloudStorage/OneDrive/"
    fi
fi

# Remove trailing slash for clean config
ONEDRIVE_ROOT="${ONEDRIVE_ROOT%/}"
echo "  OneDrive root: $ONEDRIVE_ROOT"
echo

# ─── 3. Create PM-OS subfolder in OneDrive ───────────────────────────────────

echo "Step 3: Creating PM-OS folder in OneDrive..."
PMOS_REMOTE="$ONEDRIVE_ROOT/PM-OS"
mkdir -p "$PMOS_REMOTE"
echo "  Created: $PMOS_REMOTE"
echo

# ─── 4. Generate pandoc reference template ───────────────────────────────────

echo "Step 4: Generating pandoc reference template..."
REFERENCE_DOCX="$SCRIPT_DIR/pandoc_reference.docx"

if [ ! -f "$REFERENCE_DOCX" ]; then
    pandoc -o "$REFERENCE_DOCX" --print-default-data-file reference.docx 2>/dev/null || \
    pandoc -o "$REFERENCE_DOCX" /dev/null --from=markdown --to=docx 2>/dev/null || \
    echo "  Warning: Could not generate reference.docx. Default styling will be used."
fi

if [ -f "$REFERENCE_DOCX" ]; then
    echo "  Created: $REFERENCE_DOCX"
    echo "  (Edit this file in Word to customize heading styles, fonts, etc.)"
fi
echo

# ─── 5. Write sync_config.yaml ───────────────────────────────────────────────

echo "Step 5: Writing sync_config.yaml..."
CONFIG_PATH="$SCRIPT_DIR/sync_config.yaml"

cat > "$CONFIG_PATH" << EOF
# PM-OS Document Sync Configuration
# Generated by setup_doc_sync.sh on $(date +%Y-%m-%d)

onedrive_root: "$ONEDRIVE_ROOT"
sharepoint_site: "PM-OS"
sync_enabled: true

sync_paths:
  - datasets/product/**/*.md
  - datasets/research/**/*.md
  - datasets/strategy/**/*.md

sync_exclude:
  - datasets/meetings/**
  - datasets/tasks/**
  - datasets/learning/**
EOF

echo "  Written: $CONFIG_PATH"
echo

# ─── 6. Initialize manifest ──────────────────────────────────────────────────

echo "Step 6: Initializing sync manifest..."
MANIFEST="$SCRIPT_DIR/_sync_manifest.json"
if [ ! -f "$MANIFEST" ] || [ "$(cat "$MANIFEST")" = "{}" ]; then
    echo '{}' > "$MANIFEST"
    echo "  Initialized: $MANIFEST"
else
    echo "  Manifest already exists with data, keeping it."
fi
echo

# ─── 7. Install launchd watcher ──────────────────────────────────────────────

echo "Step 7: Installing launchd watcher daemon..."

# Unload existing if present
if launchctl list "$PLIST_NAME" &>/dev/null 2>&1; then
    echo "  Stopping existing watcher..."
    launchctl unload "$PLIST_PATH" 2>/dev/null || true
fi

cat > "$PLIST_PATH" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${PLIST_NAME}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/env</string>
        <string>python3</string>
        <string>${SCRIPT_DIR}/doc_sync_watcher.py</string>
    </array>
    <key>WorkingDirectory</key>
    <string>${PM_OS_DIR}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>${PM_OS_DIR}/logs/doc_sync_watcher.log</string>
    <key>StandardErrorPath</key>
    <string>${PM_OS_DIR}/logs/doc_sync_watcher.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>
</dict>
</plist>
EOF

echo "  Written: $PLIST_PATH"

# Ensure logs directory exists
mkdir -p "$PM_OS_DIR/logs"

# Load the daemon
launchctl load "$PLIST_PATH"
echo "  Watcher daemon started."
echo

# ─── Done ─────────────────────────────────────────────────────────────────────

echo "=== Setup Complete ==="
echo
echo "Usage:"
echo "  python3 scripts/doc_sync.py sync-one datasets/product/prds/2026/example.md"
echo "  python3 scripts/doc_sync.py status"
echo "  python3 scripts/doc_sync.py sync-all"
echo
echo "The watcher daemon will auto-sync changes bidirectionally."
echo "Logs: $PM_OS_DIR/logs/doc_sync_watcher.log"
echo
echo "To stop the watcher:  launchctl unload $PLIST_PATH"
echo "To restart:           launchctl unload $PLIST_PATH && launchctl load $PLIST_PATH"
